/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TennisRouteImport } from './routes/tennis'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as HostRouteImport } from './routes/host'
import { Route as GamesRouteImport } from './routes/games'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as IndexRouteImport } from './routes/index'

const TennisRoute = TennisRouteImport.update({
  id: '/tennis',
  path: '/tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browser': typeof BrowserRoute
  '/games': typeof GamesRoute
  '/host': typeof HostRoute
  '/phone': typeof PhoneRoute
  '/tennis': typeof TennisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browser': typeof BrowserRoute
  '/games': typeof GamesRoute
  '/host': typeof HostRoute
  '/phone': typeof PhoneRoute
  '/tennis': typeof TennisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browser': typeof BrowserRoute
  '/games': typeof GamesRoute
  '/host': typeof HostRoute
  '/phone': typeof PhoneRoute
  '/tennis': typeof TennisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browser' | '/games' | '/host' | '/phone' | '/tennis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browser' | '/games' | '/host' | '/phone' | '/tennis'
  id: '__root__' | '/' | '/browser' | '/games' | '/host' | '/phone' | '/tennis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowserRoute: typeof BrowserRoute
  GamesRoute: typeof GamesRoute
  HostRoute: typeof HostRoute
  PhoneRoute: typeof PhoneRoute
  TennisRoute: typeof TennisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tennis': {
      id: '/tennis'
      path: '/tennis'
      fullPath: '/tennis'
      preLoaderRoute: typeof TennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowserRoute: BrowserRoute,
  GamesRoute: GamesRoute,
  HostRoute: HostRoute,
  PhoneRoute: PhoneRoute,
  TennisRoute: TennisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
